// Mock data fallbacks — used when API returns empty or fails
export const VEHICLES: any[] = [
  { id: 'car', name: 'Car', model: 'Toyota Prius', image: '/vehicles/car-new.png', capacity: '3–4 pax', maxPassengers: 4, maxLuggage: 3, luggageLabel: '2–3 suitcases', pricePerDay: 45 },
  { id: 'minivan', name: 'Minivan', model: 'Toyota HiAce', image: '/vehicles/minivan-new.png', capacity: '6–7 pax', maxPassengers: 7, maxLuggage: 5, luggageLabel: '4–5 suitcases', pricePerDay: 65 },
  { id: 'large-van', name: 'Large Minivan', model: 'Toyota HiAce HR', image: '/vehicles/large-minivan-new.png', capacity: 'up to 10 pax', maxPassengers: 10, maxLuggage: 10, luggageLabel: '6–10 suitcases', pricePerDay: 85 },
  { id: 'small-bus', name: 'Small Bus', model: 'Toyota Coaster', image: '/vehicles/small-bus-new.png', capacity: 'up to 20 pax', maxPassengers: 20, maxLuggage: 15, luggageLabel: '10–15 suitcases', pricePerDay: 120 },
  { id: 'medium-bus', name: 'Medium Bus', model: 'King Long', image: '/vehicles/medium-bus-new.png', capacity: 'up to 35 pax', maxPassengers: 35, maxLuggage: 25, luggageLabel: 'up to 25 suitcases', pricePerDay: 175 },
];

export const TOURS: any[] = [
  {
    id: 'classic-sri-lanka',
    slug: 'classic-sri-lanka',
    name: 'Classic Sri Lanka',
    tagline: 'The perfect introduction to the island\'s highlights.',
    description: 'Discover the very best of Sri Lanka on this comprehensive 10-day journey. From the ancient cities of the Cultural Triangle to the misty tea plantations of the Hill Country and the golden beaches of the south coast, this tour covers the island\'s most iconic destinations with the comfort of a private driver.',
    duration: 10,
    nights: 9,
    type: 'Cultural',
    difficulty: 'Easy',
    regions: ['Cultural Triangle', 'Hill Country', 'South Coast'],
    startEnd: 'Colombo (CMB)',
    highlights: ['Sigiriya Rock Fortress', 'Temple of the Tooth', 'Tea plantation visit', 'Yala National Park safari', 'Galle Fort', 'Nine Arches Bridge'],
    images: [
      'https://images.unsplash.com/photo-1586523969032-b4d0db38124f?w=800&q=80',
      'https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=800&q=80',
      'https://images.unsplash.com/photo-1567157577867-05ccb1388e13?w=800&q=80',
    ],
    included: ['Private vehicle & driver for 10 days', 'All fuel & tolls', 'Driver accommodation & meals', 'Airport pickup & drop-off', 'Bottled water daily'],
    notIncluded: ['Hotel accommodation', 'Meals for travellers', 'Entrance fees to sites', 'Tips for driver', 'Travel insurance'],
    vehicleRates: { car: 45, minivan: 65, 'large-van': 85, 'small-bus': 120, 'medium-bus': 175 },
    addOns: [
      { id: 'airport-pickup', name: 'Airport Pickup', description: 'Meet & greet at Bandaranaike International Airport', price: 28 },
      { id: 'welcome-pack', name: 'Welcome Pack', description: 'Local SIM card, bottled water, snacks & guidebook', price: 15 },
      { id: 'safari-upgrade', name: 'Premium Safari Jeep', description: 'Upgrade to a private jeep for Yala safari', price: 45 },
    ],
    leadTimeDays: 3,
    itinerary: [
      { day: 1, title: 'Airport to Negombo', location: 'Negombo', description: 'Your driver meets you at Bandaranaike International Airport and transfers you to your beachside hotel in Negombo.', drivingTime: '30 minutes', stops: ['Bandaranaike Airport', 'Negombo Beach', 'Dutch Canal'] },
      { day: 2, title: 'Negombo to Anuradhapura', location: 'Anuradhapura', description: 'Journey north to the ancient capital of Anuradhapura, a UNESCO World Heritage Site.', drivingTime: '4 hours', stops: ['Sri Maha Bodhi', 'Ruwanwelisaya Dagoba', 'Jetavanaramaya'] },
      { day: 3, title: 'Anuradhapura to Sigiriya', location: 'Sigiriya', description: 'Climb the iconic Lion Rock fortress, a 5th-century palace perched atop a 200-metre rock column.', drivingTime: '2 hours', stops: ['Sigiriya Rock Fortress', 'Sigiriya Frescoes', 'Dambulla Cave Temple'] },
      { day: 4, title: 'Sigiriya to Polonnaruwa & Minneriya', location: 'Sigiriya', description: 'Explore the medieval capital of Polonnaruwa. Afternoon jeep safari at Minneriya.', drivingTime: '1.5 hours', stops: ['Polonnaruwa Ancient City', 'Gal Vihara', 'Minneriya National Park'] },
      { day: 5, title: 'Sigiriya to Kandy', location: 'Kandy', description: 'Wind through the lush countryside to Kandy. Kandyan dance performance and Temple of the Tooth.', drivingTime: '3 hours', stops: ['Matale Spice Garden', 'Temple of the Tooth', 'Kandy Lake'] },
      { day: 6, title: 'Kandy to Nuwara Eliya', location: 'Nuwara Eliya', description: 'Drive into the misty highlands past emerald tea plantations. Visit a working tea factory.', drivingTime: '2.5 hours', stops: ['Ramboda Falls', 'Tea Factory Visit', 'Gregory Lake'] },
      { day: 7, title: 'Nuwara Eliya to Ella', location: 'Ella', description: 'One of the most scenic drives in Sri Lanka. The famous Nine Arches Bridge.', drivingTime: '2 hours', stops: ['Nine Arches Bridge', 'Ella Gap Viewpoint', 'Ravana Falls'] },
      { day: 8, title: 'Ella to Yala', location: 'Yala', description: 'Descend from the highlands to Yala, home to the highest density of leopards in the world.', drivingTime: '3 hours', stops: ['Buduruwagala Temple', 'Yala National Park Safari'] },
      { day: 9, title: 'Yala to Galle', location: 'Galle', description: 'Drive along the stunning southern coast to the UNESCO-listed Galle Fort.', drivingTime: '3 hours', stops: ['Mirissa Beach', 'Galle Fort', 'Flag Rock Bastion'] },
      { day: 10, title: 'Galle to Airport', location: 'Colombo', description: 'Scenic coastal road back to Colombo and the airport.', drivingTime: '2.5 hours', stops: ['Bentota Beach', 'Colombo (optional)', 'Bandaranaike Airport'] },
    ],
  },
  {
    id: 'wild-sri-lanka',
    slug: 'wild-sri-lanka',
    name: 'Wild Sri Lanka',
    tagline: 'Leopards, elephants, and untouched wilderness.',
    description: 'An 8-day wildlife-focused adventure across Sri Lanka\'s best national parks. Track leopards in Yala, watch elephants gather at Minneriya, explore the wetlands of Bundala, and discover the marine wonders of Mirissa.',
    duration: 8,
    nights: 7,
    type: 'Wildlife',
    difficulty: 'Moderate',
    regions: ['Cultural Triangle', 'South Coast', 'East Coast'],
    startEnd: 'Colombo (CMB)',
    highlights: ['Yala leopard safari', 'Minneriya elephant gathering', 'Whale watching in Mirissa', 'Bundala bird sanctuary', 'Udawalawe elephant safari'],
    images: [
      'https://images.unsplash.com/photo-1535338454528-1b4ac38b083e?w=800&q=80',
      'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    ],
    included: ['Private vehicle & driver for 8 days', 'All fuel & tolls', 'Driver accommodation & meals', 'Airport pickup & drop-off', 'Bottled water daily'],
    notIncluded: ['Hotel accommodation', 'Meals for travellers', 'National park entrance fees', 'Safari jeep hire', 'Tips for driver'],
    vehicleRates: { car: 45, minivan: 65, 'large-van': 85, 'small-bus': 120, 'medium-bus': 175 },
    addOns: [
      { id: 'airport-pickup', name: 'Airport Pickup', description: 'Meet & greet at Bandaranaike International Airport', price: 28 },
      { id: 'whale-watching', name: 'Whale Watching Trip', description: 'Early morning boat trip from Mirissa harbour', price: 55 },
      { id: 'photo-guide', name: 'Photography Guide', description: 'Professional wildlife photography guide for one safari', price: 85 },
    ],
    leadTimeDays: 5,
    itinerary: [
      { day: 1, title: 'Airport to Habarana', location: 'Habarana', description: 'Transfer to Habarana, the gateway to the Cultural Triangle.', drivingTime: '4 hours', stops: ['Bandaranaike Airport', 'Habarana'] },
      { day: 2, title: 'Minneriya Safari & Sigiriya', location: 'Habarana', description: 'Sigiriya Rock Fortress in the morning, Minneriya elephant gathering in the afternoon.', drivingTime: '1 hour', stops: ['Sigiriya Rock Fortress', 'Minneriya National Park'] },
      { day: 3, title: 'Habarana to Knuckles Range', location: 'Kandy', description: 'Trek through UNESCO cloud forests with endemic birds and rare orchids.', drivingTime: '3 hours', stops: ['Knuckles Mountain Range', 'Cloud Forest Trek'] },
      { day: 4, title: 'Kandy to Udawalawe', location: 'Udawalawe', description: 'Afternoon safari to see herds of wild elephants in Udawalawe.', drivingTime: '4 hours', stops: ['Udawalawe National Park Safari', 'Elephant Transit Home'] },
      { day: 5, title: 'Udawalawe to Yala', location: 'Yala', description: 'Yala — world\'s highest leopard density, plus sloth bears and crocodiles.', drivingTime: '2 hours', stops: ['Yala National Park', 'Leopard Safari'] },
      { day: 6, title: 'Yala & Bundala', location: 'Yala', description: 'Morning Yala safari, afternoon Bundala Ramsar wetland with flamingos.', drivingTime: '1 hour', stops: ['Yala Morning Safari', 'Bundala National Park'] },
      { day: 7, title: 'Yala to Mirissa', location: 'Mirissa', description: 'South coast drive to Mirissa with optional whale watching.', drivingTime: '2.5 hours', stops: ['Mirissa Beach', 'Whale Watching (seasonal)', 'Coconut Tree Hill'] },
      { day: 8, title: 'Mirissa to Airport', location: 'Colombo', description: 'Final coastal drive back to the airport.', drivingTime: '3.5 hours', stops: ['Turtle Hatchery', 'Madu River (optional)', 'Bandaranaike Airport'] },
    ],
  },
  {
    id: 'beaches-and-culture',
    slug: 'beaches-and-culture',
    name: 'Beaches & Culture',
    tagline: 'Golden sands meet ancient wonders.',
    description: 'A 12-day journey that perfectly balances Sri Lanka\'s rich cultural heritage with its stunning coastline. Explore ancient temples and colonial forts, then unwind on palm-fringed beaches.',
    duration: 12,
    nights: 11,
    type: 'Mix',
    difficulty: 'Easy',
    regions: ['West Coast', 'Cultural Triangle', 'East Coast', 'South Coast'],
    startEnd: 'Colombo (CMB)',
    highlights: ['Galle Fort sunset walk', 'Trincomalee beaches', 'Sigiriya Rock', 'Mirissa whale watching', 'Unawatuna snorkelling', 'Polonnaruwa ruins'],
    images: [
      'https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    ],
    included: ['Private vehicle & driver for 12 days', 'All fuel & tolls', 'Driver accommodation & meals', 'Airport pickup & drop-off', 'Bottled water daily'],
    notIncluded: ['Hotel accommodation', 'Meals for travellers', 'Entrance fees to sites', 'Water sports', 'Tips for driver'],
    vehicleRates: { car: 45, minivan: 65, 'large-van': 85, 'small-bus': 120, 'medium-bus': 175 },
    addOns: [
      { id: 'airport-pickup', name: 'Airport Pickup', description: 'Meet & greet at Bandaranaike International Airport', price: 28 },
      { id: 'snorkelling', name: 'Snorkelling Trip', description: 'Guided snorkelling at Pigeon Island or Unawatuna', price: 35 },
      { id: 'cooking-class', name: 'Sri Lankan Cooking Class', description: 'Half-day cooking class with local family', price: 40 },
    ],
    leadTimeDays: 3,
    itinerary: [
      { day: 1, title: 'Airport to Negombo', location: 'Negombo', description: 'Arrive and transfer to your beach hotel. Explore the fishing village at sunset.', drivingTime: '30 minutes', stops: ['Negombo Beach', 'Fish Market'] },
      { day: 2, title: 'Negombo to Sigiriya', location: 'Sigiriya', description: 'Climb the iconic Sigiriya Rock Fortress and explore the ancient water gardens.', drivingTime: '4 hours', stops: ['Sigiriya Rock Fortress', 'Water Gardens'] },
      { day: 3, title: 'Polonnaruwa & Village Tour', location: 'Sigiriya', description: 'Medieval capital ruins and a village life catamaran experience.', drivingTime: '1.5 hours', stops: ['Polonnaruwa Ruins', 'Village Life Experience'] },
      { day: 4, title: 'Sigiriya to Trincomalee', location: 'Trincomalee', description: 'Head to the stunning east coast and Nilaveli beach.', drivingTime: '3.5 hours', stops: ['Nilaveli Beach', 'Fort Frederick'] },
      { day: 5, title: 'Trincomalee Beach Day', location: 'Trincomalee', description: 'Pigeon Island snorkelling or the historic Koneswaram Temple on Swami Rock.', drivingTime: '30 minutes', stops: ['Pigeon Island', 'Koneswaram Temple', 'Marble Beach'] },
      { day: 6, title: 'Trincomalee to Kandy', location: 'Kandy', description: 'Cross the island to the hill capital. Temple of the Tooth and Kandyan dance.', drivingTime: '4.5 hours', stops: ['Temple of the Tooth', 'Kandy Lake', 'Kandyan Dance Show'] },
      { day: 7, title: 'Kandy & Surrounds', location: 'Kandy', description: 'Royal Botanical Gardens, tea plantation, and Kandy\'s vibrant market.', drivingTime: '1 hour', stops: ['Peradeniya Botanical Gardens', 'Tea Plantation', 'Kandy Market'] },
      { day: 8, title: 'Kandy to Ella', location: 'Ella', description: 'Scenic mountain drive through tea country to the charming hill station.', drivingTime: '3.5 hours', stops: ['Nine Arches Bridge', 'Ella Gap', 'Little Adam\'s Peak'] },
      { day: 9, title: 'Ella to South Coast', location: 'Tangalle', description: 'Descend to the tranquil south coast and Tangalle\'s secluded beaches.', drivingTime: '3 hours', stops: ['Ravana Falls', 'Tangalle Beach'] },
      { day: 10, title: 'Mirissa & Whale Watching', location: 'Mirissa', description: 'Optional whale watching trip. Day on Mirissa\'s crescent beach.', drivingTime: '1 hour', stops: ['Mirissa Beach', 'Whale Watching', 'Coconut Tree Hill'] },
      { day: 11, title: 'Galle Fort', location: 'Galle', description: 'UNESCO Galle Fort, boutique shops, galleries, and sunset on the ramparts.', drivingTime: '45 minutes', stops: ['Galle Fort', 'Dutch Reformed Church', 'Flag Rock', 'Unawatuna Beach'] },
      { day: 12, title: 'Galle to Airport', location: 'Colombo', description: 'Scenic coastal drive to the airport.', drivingTime: '2.5 hours', stops: ['Turtle Hatchery', 'Bandaranaike Airport'] },
    ],
  },
  {
    id: 'hill-country-explorer',
    slug: 'hill-country-explorer',
    name: 'Hill Country Explorer',
    tagline: 'Rolling tea estates and misty mountain peaks.',
    description: 'A focused 7-day journey through Sri Lanka\'s breathtaking hill country. Wind through emerald tea plantations, hike to stunning viewpoints, ride the world-famous hill country train, and discover charming colonial towns.',
    duration: 7,
    nights: 6,
    type: 'Scenic',
    difficulty: 'Moderate',
    regions: ['Hill Country'],
    startEnd: 'Colombo (CMB)',
    highlights: ['Scenic train ride', 'Tea plantation tours', 'Horton Plains World\'s End', 'Adam\'s Peak sunrise', 'Knuckles Range trek', 'Nine Arches Bridge'],
    images: [
      'https://images.unsplash.com/photo-1566296440244-0e3e7b3e22ad?w=800&q=80',
      'https://images.unsplash.com/photo-1580715911453-35e13f8b3ff5?w=800&q=80',
    ],
    included: ['Private vehicle & driver for 7 days', 'All fuel & tolls', 'Driver accommodation & meals', 'Airport pickup & drop-off', 'Bottled water daily'],
    notIncluded: ['Hotel accommodation', 'Meals for travellers', 'Entrance fees to sites', 'Train tickets', 'Tips for driver'],
    vehicleRates: { car: 45, minivan: 65, 'large-van': 85, 'small-bus': 120, 'medium-bus': 175 },
    addOns: [
      { id: 'airport-pickup', name: 'Airport Pickup', description: 'Meet & greet at Bandaranaike International Airport', price: 28 },
      { id: 'train-tickets', name: 'Train Tickets', description: 'Reserved observation car seats for scenic train ride', price: 25 },
      { id: 'adams-peak-guide', name: 'Adam\'s Peak Guide', description: 'Local guide for the sunrise pilgrimage hike', price: 30 },
    ],
    leadTimeDays: 3,
    itinerary: [
      { day: 1, title: 'Airport to Kandy', location: 'Kandy', description: 'Transfer to Kandy. Temple of the Tooth in the evening.', drivingTime: '3.5 hours', stops: ['Temple of the Tooth', 'Kandy Lake'] },
      { day: 2, title: 'Kandy & Knuckles Range', location: 'Kandy', description: 'Peradeniya Botanical Gardens then afternoon trek in the Knuckles cloud forest.', drivingTime: '1.5 hours', stops: ['Peradeniya Gardens', 'Knuckles Mountain Range'] },
      { day: 3, title: 'Kandy to Nuwara Eliya', location: 'Nuwara Eliya', description: 'Drive through rolling tea estates, visiting a tea factory.', drivingTime: '2.5 hours', stops: ['Tea Factory Visit', 'Ramboda Falls', 'Gregory Lake'] },
      { day: 4, title: 'Horton Plains', location: 'Nuwara Eliya', description: 'Pre-dawn hike to World\'s End — a sheer cliff with 880m panoramic views.', drivingTime: '1 hour', stops: ['Horton Plains', 'World\'s End', 'Baker\'s Falls'] },
      { day: 5, title: 'Nuwara Eliya to Ella (Train)', location: 'Ella', description: 'The world-famous scenic train ride. Nine Arches Bridge at sunset.', drivingTime: 'Train: 3 hours', stops: ['Scenic Train Ride', 'Nine Arches Bridge', 'Ella Town'] },
      { day: 6, title: 'Ella Adventures', location: 'Ella', description: 'Little Adam\'s Peak hike, Ravana Falls, and Ella\'s charming cafés.', drivingTime: '30 minutes', stops: ['Little Adam\'s Peak', 'Ravana Falls', 'Ella Rock (optional)'] },
      { day: 7, title: 'Ella to Airport', location: 'Colombo', description: 'Drive back through the highlands to the airport.', drivingTime: '5 hours', stops: ['Buduruwagala Temple', 'Bandaranaike Airport'] },
    ],
  },
];

export const TRANSFERS: any[] = [
  // Airport routes
  { id: 'cmb-colombo', from: 'Bandaranaike Int. Airport (CMB)', to: 'Colombo City', distance: '35 km', time: '1–1.5 hours', prices: { car: 28, minivan: 38, 'large-van': 48, 'small-bus': 65, 'medium-bus': 95 } },
  { id: 'cmb-kandy', from: 'Bandaranaike Int. Airport (CMB)', to: 'Kandy', distance: '120 km', time: '3–3.5 hours', prices: { car: 66, minivan: 90, 'large-van': 114, 'small-bus': 144, 'medium-bus': 180 } },
  { id: 'cmb-galle', from: 'Bandaranaike Int. Airport (CMB)', to: 'Galle', distance: '165 km', time: '3–4 hours', prices: { car: 91, minivan: 124, 'large-van': 157, 'small-bus': 198, 'medium-bus': 248 } },
  { id: 'cmb-sigiriya', from: 'Bandaranaike Int. Airport (CMB)', to: 'Sigiriya', distance: '175 km', time: '4–4.5 hours', prices: { car: 96, minivan: 131, 'large-van': 166, 'small-bus': 210, 'medium-bus': 263 } },
  { id: 'cmb-ella', from: 'Bandaranaike Int. Airport (CMB)', to: 'Ella', distance: '270 km', time: '6–7 hours', prices: { car: 149, minivan: 203, 'large-van': 257, 'small-bus': 324, 'medium-bus': 405 } },
  { id: 'cmb-negombo', from: 'Bandaranaike Int. Airport (CMB)', to: 'Negombo', distance: '10 km', time: '20–30 minutes', prices: { car: 12, minivan: 16, 'large-van': 20, 'small-bus': 28, 'medium-bus': 38 } },
  // Popular inter-city routes
  { id: 'colombo-galle', from: 'Colombo', to: 'Galle', distance: '130 km', time: '2.5–3 hours', prices: { car: 72, minivan: 98, 'large-van': 124, 'small-bus': 156, 'medium-bus': 195 } },
  { id: 'colombo-kandy', from: 'Colombo', to: 'Kandy', distance: '120 km', time: '3–3.5 hours', prices: { car: 66, minivan: 90, 'large-van': 114, 'small-bus': 144, 'medium-bus': 180 } },
  { id: 'colombo-sigiriya', from: 'Colombo', to: 'Sigiriya', distance: '170 km', time: '4–4.5 hours', prices: { car: 94, minivan: 128, 'large-van': 162, 'small-bus': 204, 'medium-bus': 255 } },
  { id: 'kandy-ella', from: 'Kandy', to: 'Ella', distance: '140 km', time: '4–5 hours', prices: { car: 77, minivan: 105, 'large-van': 133, 'small-bus': 168, 'medium-bus': 210 } },
  { id: 'galle-ella', from: 'Galle', to: 'Ella', distance: '200 km', time: '5–6 hours', prices: { car: 110, minivan: 150, 'large-van': 190, 'small-bus': 240, 'medium-bus': 300 } },
];

export const POPULAR_ROUTES: any[] = [
  { id: 'colombo-galle', from: 'Colombo', to: 'Galle', distance: 130, estimatedTime: '2.5–3 hours', prices: { car: 72, minivan: 98, 'large-van': 124, 'small-bus': 156, 'medium-bus': 195 }, description: 'Scenic coastal drive along the southern expressway to the historic Dutch fort city.' },
  { id: 'colombo-kandy', from: 'Colombo', to: 'Kandy', distance: 120, estimatedTime: '3–3.5 hours', prices: { car: 66, minivan: 90, 'large-van': 114, 'small-bus': 144, 'medium-bus': 180 }, description: 'Journey through lush hill country to Sri Lanka\'s cultural capital and the Temple of the Tooth.' },
  { id: 'colombo-sigiriya', from: 'Colombo', to: 'Sigiriya', distance: 170, estimatedTime: '4–4.5 hours', prices: { car: 94, minivan: 128, 'large-van': 162, 'small-bus': 204, 'medium-bus': 255 }, description: 'Travel to the ancient rock fortress, a UNESCO World Heritage Site rising from the jungle.' },
  { id: 'kandy-ella', from: 'Kandy', to: 'Ella', distance: 140, estimatedTime: '4–5 hours', prices: { car: 77, minivan: 105, 'large-van': 133, 'small-bus': 168, 'medium-bus': 210 }, description: 'Wind through tea plantations and misty mountains to the charming hill station of Ella.' },
  { id: 'galle-ella', from: 'Galle', to: 'Ella', distance: 200, estimatedTime: '5–6 hours', prices: { car: 110, minivan: 150, 'large-van': 190, 'small-bus': 240, 'medium-bus': 300 }, description: 'From the coastal fort town, climb into the highlands past waterfalls and paddy fields.' },
];

export const CURRENCIES: any[] = [];
export const BOOKINGS: any[] = [];
export const CYO_REQUESTS: any[] = [];
export const DRIVER_PROFILE = null;
export const DRIVER_BOOKINGS: any[] = [];

// ── Tour Groups (fallback when API is unavailable) ────────────────────────────
// vehicleRates is array format to match API shape expected by TourGroupCard
const VR = (car: number, minivan: number, largeVan: number, smallBus: number, mediumBus: number) => [
  { vehicleType: 'car', pricePerDay: car },
  { vehicleType: 'minivan', pricePerDay: minivan },
  { vehicleType: 'large-van', pricePerDay: largeVan },
  { vehicleType: 'small-bus', pricePerDay: smallBus },
  { vehicleType: 'medium-bus', pricePerDay: mediumBus },
];

export const MOCK_TOUR_GROUPS: any[] = [
  // ── Tour 1: Classic Sri Lanka ────────────────────────────────────────────────
  {
    groupId: 'group-classic-sri-lanka',
    groupSlug: 'classic-sri-lanka',
    name: 'Classic Sri Lanka',
    tagline: "Sri Lanka's bucket list — culture, beaches, wildlife, scenery & food.",
    description: 'The definitive Sri Lanka journey. Ancient rock fortresses, misty tea estates, golden southern beaches, wildlife safaris and legendary food — all with your own private driver.',
    bestFor: 'First-time visitors, couples, families, mixed interests',
    regions: ['Cultural Triangle', 'Hill Country', 'South Coast'],
    difficulty: 'Easy',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69f0213d520997a1cb7d8db1_Sigiriya.png'],
    highlights: ['Culture', 'Wildlife', 'Hill Country', 'Beaches', 'Food'],
    sortOrder: 1,
    variants: [
      {
        id: 'classic-sri-lanka-5d', slug: 'classic-sri-lanka-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Sigiriya/Dambulla', location: 'Sigiriya', description: 'Drive from Colombo to the Cultural Triangle. Evening village experience and relaxation.', stops: ['Colombo', 'Cultural Triangle', 'Village experience'] },
          { dayNumber: 2, title: 'Sigiriya', location: 'Sigiriya', description: 'Early morning climb of Sigiriya Rock Fortress. Afternoon safari in Minneriya National Park.', stops: ['Sigiriya Rock Fortress', 'Minneriya National Park'] },
          { dayNumber: 3, title: 'Sigiriya → Kandy', location: 'Kandy', description: 'Visit Dambulla Cave Temple en route. Drive to Kandy. Evening: Temple of the Tooth Relic.', stops: ['Dambulla Cave Temple', 'Temple of the Tooth Relic', 'Kandy'] },
          { dayNumber: 4, title: 'Kandy/Hill Country → Ella', location: 'Ella', description: 'Scenic train journey from Kandy to Ella (*check availability). Visit Nine Arches Bridge on arrival.', stops: ['Kandy to Ella scenic train (*check availability)', 'Nine Arches Bridge'] },
          { dayNumber: 5, title: 'Ella → South Coast → Colombo', location: 'Colombo', description: 'Drive to the south coast (Bentota/Mirissa) with an optional quick beach stop before returning to Colombo / airport.', stops: ['South Coast (Bentota/Mirissa)', 'Optional beach stop', 'Colombo / airport'] },
        ],
      },
      {
        id: 'classic-sri-lanka-7d', slug: 'classic-sri-lanka-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Sigiriya/Dambulla', location: 'Sigiriya', description: 'Drive from Colombo to the Cultural Triangle. Evening village experience and relaxation.', stops: ['Colombo', 'Cultural Triangle', 'Village experience'] },
          { dayNumber: 2, title: 'Sigiriya', location: 'Sigiriya', description: 'Climb Sigiriya Rock Fortress. Afternoon safari in Minneriya National Park.', stops: ['Sigiriya Rock Fortress', 'Minneriya National Park safari'] },
          { dayNumber: 3, title: 'Sigiriya → Kandy', location: 'Kandy', description: 'Visit Dambulla Cave Temple. Continue to Kandy: Temple of the Tooth, Royal Botanic Gardens at Peradeniya, and a traditional cultural dance show.', stops: ['Dambulla Cave Temple', 'Temple of the Tooth', 'Royal Botanic Gardens Peradeniya', 'Cultural dance show'] },
          { dayNumber: 4, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Drive into the hill country. Visit tea plantations and a tea factory. Enjoy the cooler climate of Nuwara Eliya.', stops: ['Tea plantations', 'Tea factory visit', 'Nuwara Eliya'] },
          { dayNumber: 5, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic Kandy to Ella train journey (*check availability). Visit Nine Arches Bridge. Hike Little Adam\'s Peak.', stops: ['Kandy to Ella scenic train (*check availability)', 'Nine Arches Bridge', 'Little Adam\'s Peak hike'] },
          { dayNumber: 6, title: 'Ella → South Coast (Mirissa/Bentota)', location: 'South Coast', description: 'Drive to the south coast for beach relaxation. Optional whale watching excursion in Mirissa (seasonal).', stops: ['South Coast (Mirissa/Bentota)', 'Beach relaxation', 'Whale watching Mirissa (seasonal)'] },
          { dayNumber: 7, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops to explore other beaches along the way.', stops: ['Optional beach stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'classic-sri-lanka-10d', slug: 'classic-sri-lanka-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Sigiriya/Dambulla', location: 'Sigiriya', description: 'Drive from Colombo to the Cultural Triangle. Evening village experience and relaxation.', stops: ['Colombo', 'Cultural Triangle', 'Village experience'] },
          { dayNumber: 2, title: 'Sigiriya', location: 'Sigiriya', description: 'Climb Sigiriya Rock Fortress. Afternoon safari in Minneriya National Park.', stops: ['Sigiriya Rock Fortress', 'Minneriya National Park safari'] },
          { dayNumber: 3, title: 'Sigiriya → Polonnaruwa → Kandy', location: 'Kandy', description: 'Visit the ancient city of Polonnaruwa before continuing to Kandy.', stops: ['Polonnaruwa Ancient City', 'Kandy'] },
          { dayNumber: 4, title: 'Kandy', location: 'Kandy', description: 'Explore Kandy: visit the Temple of the Tooth, walk around the lake, and enjoy the Royal Botanic Gardens.', stops: ['Temple of the Tooth', 'Kandy Lake walk', 'Royal Botanic Gardens'] },
          { dayNumber: 5, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Immerse in tea country. Visit Gregory Lake for boat rides and walks.', stops: ['Tea country immersion', 'Tea plantations & factory', 'Gregory Lake'] },
          { dayNumber: 6, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic Kandy to Ella train (*check availability). Visit Nine Arches Bridge.', stops: ['Kandy to Ella scenic train (*check availability)', 'Nine Arches Bridge'] },
          { dayNumber: 7, title: 'Ella', location: 'Ella', description: 'Hike Little Adam\'s Peak and explore Ella\'s beautiful waterfalls.', stops: ['Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 8, title: 'Ella → Udawalawe → South Coast', location: 'South Coast', description: 'Safari at Udawalawe National Park, then continue to the south coast.', stops: ['Udawalawe National Park safari', 'South Coast'] },
          { dayNumber: 9, title: 'South Coast (Beach Day)', location: 'South Coast', description: 'Relax and/or visit other beaches. Whale watching (seasonal). Surfing.', stops: ['Beach relaxation', 'Whale watching (seasonal)', 'Surfing'] },
          { dayNumber: 10, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'classic-sri-lanka-14d', slug: 'classic-sri-lanka-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Sigiriya', location: 'Sigiriya', description: 'Drive from Colombo to the Cultural Triangle.', stops: ['Colombo', 'Cultural Triangle'] },
          { dayNumber: 2, title: 'Sigiriya', location: 'Sigiriya', description: 'Climb Sigiriya Rock Fortress and Pidurangala Rock. Visit Dambulla Cave Temple.', stops: ['Sigiriya Rock Fortress', 'Pidurangala Rock', 'Dambulla Cave Temple'] },
          { dayNumber: 3, title: 'Sigiriya (Polonnaruwa)', location: 'Sigiriya', description: 'Visit Polonnaruwa Ancient City. Afternoon safari in Minneriya National Park.', stops: ['Polonnaruwa Ancient City', 'Minneriya National Park safari'] },
          { dayNumber: 4, title: 'Sigiriya → Kandy', location: 'Kandy', description: 'Visit Dambulla Cave Temple, then drive to Kandy. Enjoy the lake walk and Royal Botanic Gardens.', stops: ['Dambulla Cave Temple', 'Kandy Lake walk', 'Royal Botanic Gardens'] },
          { dayNumber: 5, title: 'Kandy', location: 'Kandy', description: 'Visit the Temple of the Tooth and hike to Bahirawakanda Buddha Statue. Explore Udawattakele Sanctuary — ideal for bird watching.', stops: ['Temple of the Tooth', 'Bahirawakanda Buddha Statue hike', 'Udawattakele Sanctuary (bird watching)'] },
          { dayNumber: 6, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Stop at Ramboda Waterfall. Visit tea plantations and a tea factory. Hike Horton Plains (World\'s End & Baker\'s Falls). Relax at Gregory Lake.', stops: ['Ramboda Waterfall', 'Tea plantations & factory', 'Horton Plains — World\'s End & Baker\'s Falls', 'Gregory Lake'] },
          { dayNumber: 7, title: 'Nuwara Eliya', location: 'Nuwara Eliya', description: 'Visit Seeta Amman Kovil and explore Hakgala Botanical Garden.', stops: ['Seeta Amman Kovil', 'Hakgala Botanical Garden'] },
          { dayNumber: 8, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic Kandy to Ella train (*check availability). Visit Nine Arches Bridge.', stops: ['Kandy to Ella scenic train (*check availability)', 'Nine Arches Bridge'] },
          { dayNumber: 9, title: 'Ella', location: 'Ella', description: 'Hike Little Adam\'s Peak and explore Ella\'s beautiful waterfalls.', stops: ['Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 10, title: 'Ella → Yala', location: 'Yala', description: 'Drive to Yala National Park / Tissamaharama.', stops: ['Yala National Park', 'Tissamaharama'] },
          { dayNumber: 11, title: 'Yala → South Coast (Mirissa/Unawatuna/Bentota)', location: 'South Coast', description: 'Leisurely morning at Yala, then drive to the south coast.', stops: ['Yala morning', 'South Coast (Mirissa/Unawatuna/Bentota)'] },
          { dayNumber: 12, title: 'South Coast (Beach Day)', location: 'South Coast', description: 'Visit Galle Fort. Surfing. Relax and/or visit other beaches. Whale watching (seasonal).', stops: ['Galle Fort', 'Surfing', 'Whale watching (seasonal)'] },
          { dayNumber: 13, title: 'South Coast (Beach Day)', location: 'South Coast', description: 'Relax and/or visit other beaches. Turtle season (Nov–Apr/May; hatching Jan & Mar) — Rekawa Beach (Tangalle), Kosgoda, Mirissa, Bentota.', stops: ['Beach relaxation', 'Turtle watching (seasonal — Rekawa Beach, Kosgoda, Mirissa, Bentota)'] },
          { dayNumber: 14, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 2: North & East Sri Lanka ──────────────────────────────────────────
  {
    groupId: 'group-north-east-sri-lanka',
    groupSlug: 'north-east-sri-lanka',
    name: 'North & East Sri Lanka',
    tagline: 'Jaffna & Trinco, Nilaveli, Arugam Bay — culture & scenery.',
    description: 'Venture off the beaten path to Sri Lanka\'s untouched north and east — Tamil culture in Jaffna, pristine beaches in Trincomalee and Nilaveli, and the world-famous surf of Arugam Bay.',
    bestFor: 'Adventurous travellers & cultural explorers',
    regions: ['North Sri Lanka', 'East Coast'],
    difficulty: 'Moderate',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69f022e3d67ac0f302daa5f2_Jaffna.png'],
    highlights: ['Untouched Beaches', 'Tamil Culture', 'Off-the-Beaten-Path'],
    sortOrder: 2,
    variants: [
      {
        id: 'north-east-sri-lanka-5d', slug: 'north-east-sri-lanka-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Jaffna', location: 'Jaffna', description: 'Early departure, scenic drive north. Explore Jaffna city on arrival.', stops: ['Colombo', 'Jaffna city'] },
          { dayNumber: 2, title: 'Jaffna', location: 'Jaffna', description: 'Visit Nallur Kandaswamy Temple and Jaffna Fort. Experience authentic north Sri Lankan cuisine.', stops: ['Nallur Kandaswamy Temple', 'Jaffna Fort', 'North cuisine experience'] },
          { dayNumber: 3, title: 'Jaffna → Trincomalee / Nilaveli', location: 'Nilaveli / Trincomalee', description: 'Travel to the east coast. Relax on Nilaveli Beach.', stops: ['Nilaveli Beach', 'Trincomalee'] },
          { dayNumber: 4, title: 'Trincomalee (Beaches & Culture)', location: 'Trincomalee', description: 'Visit Koneswaram Temple. Optional snorkelling near Pigeon Island. Whale watching at Swami Rock.', stops: ['Koneswaram Temple', 'Pigeon Island snorkelling (optional)', 'Whale watching — Swami Rock'] },
          { dayNumber: 5, title: 'Trincomalee → Colombo', location: 'Colombo', description: 'Return to Colombo / airport.', stops: ['Colombo / airport'] },
        ],
      },
      {
        id: 'north-east-sri-lanka-7d', slug: 'north-east-sri-lanka-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'CMB → Anuradhapura → Jaffna', location: 'Jaffna', description: 'Drive north with an optional stop at the ancient city of Anuradhapura before continuing to Jaffna.', stops: ['Anuradhapura (optional stop)', 'Jaffna'] },
          { dayNumber: 2, title: 'Jaffna', location: 'Jaffna', description: 'Nallur Kandaswamy Temple, Fort & Delft/Nainativu islands. Explore local markets and sample north cuisine.', stops: ['Nallur Kandaswamy Temple', 'Fort & Delft/Nainativu islands', 'Local markets & north cuisine'] },
          { dayNumber: 3, title: 'Jaffna → Trincomalee', location: 'Nilaveli / Trincomalee', description: 'Travel along the scenic northeast coast. Relax on Nilaveli or another beach.', stops: ['Scenic northeast drive', 'Nilaveli/other beach'] },
          { dayNumber: 4, title: 'Trincomalee (Beaches & Culture)', location: 'Trincomalee', description: 'Visit Koneswaram Temple. Snorkelling excursion. Whale watching at Swami Rock.', stops: ['Koneswaram Temple', 'Snorkelling excursion', 'Whale watching — Swami Rock'] },
          { dayNumber: 5, title: 'Trincomalee → Pasikudah', location: 'Pasikudah', description: 'Drive to Pasikudah. Beach activities. Visit Batticaloa Fort / Kallady Bridge.', stops: ['Beach activities', 'Batticaloa Fort', 'Kallady Bridge'] },
          { dayNumber: 6, title: 'Pasikudah (Beach Day)', location: 'Pasikudah', description: 'Relax on the beach or try surfing. Visit the quieter Kalkudah beach. Optional visit to Batticaloa Fort / Kallady Bridge.', stops: ['Pasikudah beach', 'Kalkudah beach', 'Batticaloa Fort / Kallady Bridge (optional)'] },
          { dayNumber: 7, title: 'Pasikudah → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops en route. Transfer to airport or continue with other travel.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'north-east-sri-lanka-10d', slug: 'north-east-sri-lanka-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Anuradhapura', location: 'Anuradhapura', description: 'Travel north to Anuradhapura.', stops: ['Anuradhapura'] },
          { dayNumber: 2, title: 'Anuradhapura → Jaffna', location: 'Jaffna', description: 'Explore the ancient ruins of Anuradhapura before continuing to Jaffna.', stops: ['Anuradhapura ancient ruins', 'Jaffna'] },
          { dayNumber: 3, title: 'Jaffna', location: 'Jaffna', description: 'Nallur Kandaswamy Temple, Fort & Delft/Nainativu islands. Local markets and north cuisine.', stops: ['Nallur Kandaswamy Temple', 'Fort & Delft/Nainativu islands', 'Local markets & north cuisine'] },
          { dayNumber: 4, title: 'Jaffna → Trincomalee', location: 'Nilaveli / Trincomalee', description: 'Travel along the scenic northeast. Relax on Nilaveli or another beach.', stops: ['Scenic northeast drive', 'Nilaveli/other beach'] },
          { dayNumber: 5, title: 'Trincomalee (Beaches & Culture)', location: 'Trincomalee', description: 'Koneswaram Temple and snorkelling. Whale watching at Swami Rock.', stops: ['Koneswaram Temple', 'Snorkelling', 'Whale watching — Swami Rock'] },
          { dayNumber: 6, title: 'Nilaveli (Beach & Marine Activities)', location: 'Nilaveli / Trincomalee', description: 'Relax on Nilaveli beach. Visit Pigeon Island Marine Park for snorkelling / diving.', stops: ['Nilaveli beach', 'Pigeon Island Marine Park', 'Snorkelling / diving'] },
          { dayNumber: 7, title: 'Trincomalee → Pasikudah', location: 'Pasikudah', description: 'Beach activities. Visit Batticaloa Fort / Kallady Bridge.', stops: ['Beach activities', 'Batticaloa Fort', 'Kallady Bridge'] },
          { dayNumber: 8, title: 'Pasikudah → Arugam Bay (Leisure/Surfing)', location: 'Arugam Bay', description: 'Relax on the beach or try surfing in Arugam Bay.', stops: ['Arugam Bay beach', 'Surfing'] },
          { dayNumber: 9, title: 'Arugam Bay → Colombo (via Ella or Yala — optional)', location: 'Colombo', description: 'Return to Colombo with optional scenic or wildlife stops via Ella or Yala.', stops: ['Ella (optional)', 'Yala (optional)', 'Colombo'] },
          { dayNumber: 10, title: 'Colombo', location: 'Colombo', description: 'Transfer to airport or continue with other travel.', stops: ['Colombo / airport'] },
        ],
      },
      {
        id: 'north-east-sri-lanka-14d', slug: 'north-east-sri-lanka-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Anuradhapura', location: 'Anuradhapura', description: 'Travel north to Anuradhapura.', stops: ['Anuradhapura'] },
          { dayNumber: 2, title: 'Anuradhapura', location: 'Anuradhapura', description: 'Full day exploring the sacred ancient sites of Anuradhapura.', stops: ['Anuradhapura sacred sites'] },
          { dayNumber: 3, title: 'Anuradhapura → Jaffna', location: 'Jaffna', description: 'Explore en route to Jaffna.', stops: ['En route stops', 'Jaffna'] },
          { dayNumber: 4, title: 'Jaffna', location: 'Jaffna', description: 'Nallur Kandaswamy Temple, local markets and north cuisine, Jaffna Fort.', stops: ['Nallur Kandaswamy Temple', 'Local markets & north cuisine', 'Jaffna Fort'] },
          { dayNumber: 5, title: 'Jaffna Islands Experience', location: 'Jaffna', description: 'Private boat excursion to Delft & Nainativu islands.', stops: ['Delft Island', 'Nainativu Island', 'Private boat excursion'] },
          { dayNumber: 6, title: 'Jaffna → Trincomalee', location: 'Nilaveli / Trincomalee', description: 'Travel along the scenic northeast coast. Relax on Nilaveli or another beach.', stops: ['Scenic northeast drive', 'Nilaveli/other beach'] },
          { dayNumber: 7, title: 'Trincomalee (Beaches & Culture)', location: 'Trincomalee', description: 'Visit Koneswaram Temple. Snorkelling. Whale watching at Swami Rock.', stops: ['Koneswaram Temple', 'Snorkelling', 'Whale watching — Swami Rock'] },
          { dayNumber: 8, title: 'Nilaveli/Uppuveli (Beach Day)', location: 'Nilaveli / Uppuveli', description: 'Relax on Nilaveli beach and/or explore Uppuveli and surrounding beaches.', stops: ['Nilaveli beach', 'Uppuveli beach', 'Surrounding beaches'] },
          { dayNumber: 9, title: 'Trincomalee', location: 'Trincomalee', description: 'Visit "Deer Fort" Fort Frederick. Kanniya Hot Springs. Red-Sand Beach (Arisimale).', stops: ['Fort Frederick (Deer Fort)', 'Kanniya Hot Springs', 'Red-Sand Beach Arisimale'] },
          { dayNumber: 10, title: 'Trincomalee → Pasikudah', location: 'Pasikudah', description: 'Beach activities and visit Batticaloa Fort.', stops: ['Batticaloa Fort', 'Pasikudah beach'] },
          { dayNumber: 11, title: 'Pasikudah → Arugam Bay (Leisure/Surfing)', location: 'Arugam Bay', description: 'Relax on the beach or try surfing in Arugam Bay.', stops: ['Arugam Bay beach', 'Surfing'] },
          { dayNumber: 12, title: 'Arugam Bay → Yala Safari', location: 'Yala', description: 'Safari in Yala National Park.', stops: ['Yala National Park safari'] },
          { dayNumber: 13, title: 'Yala → South Coast', location: 'South Coast', description: 'Relax and/or visit other beaches on the south coast.', stops: ['South Coast beaches'] },
          { dayNumber: 14, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 3: Coast & Culture Sri Lanka ───────────────────────────────────────
  {
    groupId: 'group-coast-culture-sri-lanka',
    groupSlug: 'coast-culture-sri-lanka',
    name: 'Coast & Culture Sri Lanka',
    tagline: 'Beach, surfing, whale watching & the cultural triangle.',
    description: 'The best of both worlds — sun-drenched southern beaches, whale watching in Mirissa, wildlife safaris, Galle Fort and the magnificent cultural sites of the highlands.',
    bestFor: 'Visitors wanting a balance of beach life and cultural landmarks',
    regions: ['South Coast', 'Hill Country', 'Cultural Triangle'],
    difficulty: 'Easy',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69f0265c2e40cc16c7533e22_Ella.png'],
    highlights: ['Beaches', 'Wildlife', 'Cultural Highlights'],
    sortOrder: 3,
    variants: [
      {
        id: 'coast-culture-sri-lanka-5d', slug: 'coast-culture-sri-lanka-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast (Mirissa/Bentota)', location: 'South Coast', description: 'Travel south and relax by the ocean.', stops: ['South Coast (Mirissa/Bentota)'] },
          { dayNumber: 2, title: 'Mirissa: Beach & Whale Watching', location: 'South Coast', description: 'Whale watching excursion in Mirissa (November–April seasonal).', stops: ['Whale watching Mirissa (Nov–Apr)', 'Mirissa beach'] },
          { dayNumber: 3, title: 'South Coast → Galle → Udawalawe', location: 'Udawalawe / Tissamaharama', description: 'Visit Galle Fort. Afternoon safari in Udawalawe National Park.', stops: ['Galle Fort', 'Udawalawe National Park safari'] },
          { dayNumber: 4, title: 'Udawalawe → Kandy', location: 'Kandy', description: 'Scenic journey to Kandy. Evening visit to Temple of the Tooth.', stops: ['Scenic drive to Kandy', 'Temple of the Tooth'] },
          { dayNumber: 5, title: 'Kandy → Colombo', location: 'Colombo', description: 'Return to Colombo / airport.', stops: ['Colombo / airport'] },
        ],
      },
      {
        id: 'coast-culture-sri-lanka-7d', slug: 'coast-culture-sri-lanka-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast', location: 'South Coast', description: 'Travel south and visit beaches.', stops: ['South Coast beaches'] },
          { dayNumber: 2, title: 'Mirissa: Beach & Whale Watching', location: 'South Coast', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 3, title: 'Galle & Coastal Exploration', location: 'South Coast', description: 'Visit Galle Fort and explore nearby beaches.', stops: ['Galle Fort', 'Nearby beaches'] },
          { dayNumber: 4, title: 'South Coast → Udawalawe', location: 'Udawalawe', description: 'Travel inland for a safari in Udawalawe National Park.', stops: ['Udawalawe National Park safari'] },
          { dayNumber: 5, title: 'Udawalawe → Ella', location: 'Ella', description: 'Journey to Ella via scenic mountain roads. Visit Nine Arches Bridge.', stops: ['Scenic mountain road', 'Nine Arches Bridge', 'Ella'] },
          { dayNumber: 6, title: 'Ella → Kandy', location: 'Kandy', description: 'Ella to Kandy train (*check availability). Visit Temple of the Tooth.', stops: ['Ella to Kandy train (*check availability)', 'Temple of the Tooth'] },
          { dayNumber: 7, title: 'Kandy → Colombo', location: 'Colombo', description: 'Return to Colombo / airport.', stops: ['Colombo / airport'] },
        ],
      },
      {
        id: 'coast-culture-sri-lanka-10d', slug: 'coast-culture-sri-lanka-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast', location: 'South Coast', description: 'Travel south and visit beaches.', stops: ['South Coast beaches'] },
          { dayNumber: 2, title: 'Mirissa: Beach & Whale Watching', location: 'South Coast', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 3, title: 'Galle & Coastal Exploration', location: 'South Coast', description: 'Visit Galle Fort and explore nearby beaches.', stops: ['Galle Fort', 'Nearby beaches'] },
          { dayNumber: 4, title: 'South Coast → Udawalawe', location: 'Udawalawe', description: 'Travel inland for a safari in Udawalawe National Park.', stops: ['Udawalawe National Park safari'] },
          { dayNumber: 5, title: 'Udawalawe → Ella', location: 'Ella', description: 'Journey to Ella via scenic mountain roads. Explore around Ella.', stops: ['Scenic mountain road', 'Ella exploration'] },
          { dayNumber: 6, title: 'Ella Exploration', location: 'Ella', description: 'Visit Nine Arches Bridge and Little Adam\'s Peak.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak'] },
          { dayNumber: 7, title: 'Ella → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Scenic train journey into tea country (*check availability).', stops: ['Scenic train to Nuwara Eliya (*check availability)'] },
          { dayNumber: 8, title: 'Nuwara Eliya → Kandy', location: 'Kandy', description: 'Explore tea plantations before continuing to Kandy.', stops: ['Tea plantations', 'Kandy'] },
          { dayNumber: 9, title: 'Kandy Cultural Experience', location: 'Kandy', description: 'Visit Temple of the Tooth.', stops: ['Temple of the Tooth'] },
          { dayNumber: 10, title: 'Kandy → Colombo', location: 'Colombo', description: 'Return to Colombo / airport.', stops: ['Colombo / airport'] },
        ],
      },
      {
        id: 'coast-culture-sri-lanka-14d', slug: 'coast-culture-sri-lanka-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(50, 70, 92, 128, 178), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast', location: 'South Coast', description: 'Travel south and visit beaches.', stops: ['South Coast beaches'] },
          { dayNumber: 2, title: 'South Coast: Beach Relaxation', location: 'South Coast', description: 'Full day relaxing by the ocean.', stops: ['South Coast beach relaxation'] },
          { dayNumber: 3, title: 'Mirissa: Beach & Whale Watching', location: 'South Coast', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 4, title: 'Galle & Coastal Exploration', location: 'South Coast', description: 'Visit Galle Fort and explore nearby beaches.', stops: ['Galle Fort', 'Nearby beaches'] },
          { dayNumber: 5, title: 'South Coast → Yala Safari', location: 'Yala', description: 'Travel to Yala National Park for a safari.', stops: ['Yala National Park safari'] },
          { dayNumber: 6, title: 'Yala → Ella', location: 'Ella', description: 'Travel into the hill country.', stops: ['Hill country drive', 'Ella'] },
          { dayNumber: 7, title: 'Ella Exploration', location: 'Ella', description: 'Visit Nine Arches Bridge and Little Adam\'s Peak.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak'] },
          { dayNumber: 8, title: 'Ella → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Scenic train journey into tea country (*check availability).', stops: ['Scenic train to Nuwara Eliya (*check availability)'] },
          { dayNumber: 9, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Explore tea plantations.', stops: ['Tea plantations'] },
          { dayNumber: 10, title: 'Nuwara Eliya → Kandy', location: 'Kandy', description: 'Explore Kandy.', stops: ['Kandy'] },
          { dayNumber: 11, title: 'Kandy Cultural Experience', location: 'Kandy', description: 'Visit Temple of the Tooth.', stops: ['Temple of the Tooth'] },
          { dayNumber: 12, title: 'Kandy → Cultural Triangle (Sigiriya)', location: 'Sigiriya', description: 'Travel north with stops en route.', stops: ['En route stops', 'Sigiriya'] },
          { dayNumber: 13, title: 'Sigiriya & Safari', location: 'South Coast', description: 'Climb Sigiriya Rock Fortress. Optional safari. Drive to south coast.', stops: ['Sigiriya Rock Fortress', 'Optional safari', 'South Coast'] },
          { dayNumber: 14, title: 'Sigiriya → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 4: Beach Life — South Coast ────────────────────────────────────────
  {
    groupId: 'group-beach-life-south-coast',
    groupSlug: 'beach-life-south-coast',
    name: 'Beach Life: South Coast',
    tagline: 'Just beaches, water-based activities and relaxation.',
    description: 'Sun, surf and pure coastal bliss along Sri Lanka\'s stunning south coast — Bentota, Hikkaduwa, Mirissa, Galle, Weligama and Tangalle, all at your own pace.',
    bestFor: 'Visitors seeking sun & fun across picturesque coastal vistas',
    regions: ['South Coast', 'Galle'],
    difficulty: 'Easy',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69f02585fd5931666ef0ce1f_Galle%20(1).png'],
    highlights: ['Beach Vibes', 'Relaxation', 'Water Activities'],
    sortOrder: 4,
    variants: [
      {
        id: 'beach-life-south-coast-5d', slug: 'beach-life-south-coast-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(45, 62, 82, 115, 160), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Bentota', location: 'Bentota', description: 'Travel south, relax by the ocean. Boat safari on Madu Ganga River.', stops: ['Bentota', 'Madu Ganga River boat safari'] },
          { dayNumber: 2, title: 'Bentota/Hikkaduwa/Unawatuna — Beach Relaxation & Water Sports', location: 'Bentota', description: 'Beaches and optional water sports: jet ski, paddleboarding, snorkelling.', stops: ['Bentota / Hikkaduwa / Unawatuna beaches', 'Jet ski', 'Paddleboarding', 'Snorkelling'] },
          { dayNumber: 3, title: 'Galle/Mirissa & Surrounds — Beach Leisure & Whale Watching', location: 'Mirissa', description: 'Whale watching in Mirissa. Beach relaxation. Coconut Tree Hill for sunset.', stops: ['Whale watching — Mirissa', 'Coconut Tree Hill sunset'] },
          { dayNumber: 4, title: 'Galle & Coastal Exploration', location: 'Mirissa', description: 'Explore Galle Fort. Relaxed coastal afternoon.', stops: ['Galle Fort', 'Coastal afternoon'] },
          { dayNumber: 5, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time available.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-south-coast-7d', slug: 'beach-life-south-coast-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(45, 62, 82, 115, 160), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Bentota', location: 'Bentota', description: 'Travel south. Relax and/or boat safari.', stops: ['Bentota', 'Boat safari (optional)'] },
          { dayNumber: 2, title: 'Unawatuna & Kosgoda — Beaches & Turtles', location: 'Bentota / Galle', description: 'Visit Turtle Conservation Project. Jungle Beach or other beaches.', stops: ['Turtle Conservation Project', 'Jungle Beach'] },
          { dayNumber: 3, title: 'Mirissa', location: 'Galle / Mirissa', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 4, title: 'Galle & Coastal Exploration', location: 'Galle', description: 'Explore Galle Fort. Relaxed coastal afternoon.', stops: ['Galle Fort', 'Coastal afternoon'] },
          { dayNumber: 5, title: 'Koggala & Weligama Bay', location: 'Galle / Weligama', description: 'See stilt fishermen and turtle hatchery en route. Weligama — golden sand and surf.', stops: ['Stilt fishermen', 'Turtle hatchery', 'Weligama — golden sand & surf'] },
          { dayNumber: 6, title: 'Tangalle Beach Relaxation', location: 'Galle / Tangalle', description: 'Relax at Goyambokka or Silent Beach.', stops: ['Goyambokka Beach', 'Silent Beach'] },
          { dayNumber: 7, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-south-coast-10d', slug: 'beach-life-south-coast-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(45, 62, 82, 115, 160), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Bentota', location: 'Bentota', description: 'Travel south. Relax and/or boat safari.', stops: ['Bentota', 'Boat safari (optional)'] },
          { dayNumber: 2, title: 'Bentota Day & Surrounds', location: 'Bentota', description: 'Beaches and water sports. Brief Garden. Mask museum / market stalls.', stops: ['Beaches & water sports', 'Brief Garden', 'Mask museum / market stalls'] },
          { dayNumber: 3, title: 'Hikkaduwa/Unawatuna', location: 'Bentota / Galle', description: 'Hikkaduwa National Park coral reef. Beach relaxation and/or exploration. Tsunami museum.', stops: ['Hikkaduwa National Park reef', 'Tsunami museum'] },
          { dayNumber: 4, title: 'Unawatuna & Kosgoda', location: 'Bentota / Galle', description: 'Turtle Conservation Project. Jungle Beach or other beaches.', stops: ['Turtle Conservation Project', 'Jungle Beach'] },
          { dayNumber: 5, title: 'Mirissa', location: 'Galle / Mirissa', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 6, title: 'Galle & Coastal Exploration', location: 'Galle', description: 'Explore Galle Fort. Relaxed coastal afternoon.', stops: ['Galle Fort', 'Coastal afternoon'] },
          { dayNumber: 7, title: 'Koggala & Dikwella', location: 'South Coast', description: 'Boat safari to Cinnamon Island. Stilt fishermen, turtles, Hiriketiya Bay. Cooking classes.', stops: ['Cinnamon Island boat safari', 'Stilt fishermen', 'Turtles', 'Hiriketiya Bay', 'Cooking classes'] },
          { dayNumber: 8, title: 'Dikwella / Weligama Bay', location: 'South Coast', description: 'Beach relaxation and activities. Blue Beach Island, Nilwella.', stops: ['Dikwella / Weligama bay', 'Blue Beach Island', 'Nilwella'] },
          { dayNumber: 9, title: 'Tangalle Beach Relaxation', location: 'South Coast', description: 'Relax at Goyambokka or Silent Beach.', stops: ['Goyambokka Beach', 'Silent Beach'] },
          { dayNumber: 10, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-south-coast-14d', slug: 'beach-life-south-coast-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(45, 62, 82, 115, 160), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Bentota', location: 'Bentota', description: 'Travel south. Relax and/or boat safari.', stops: ['Bentota', 'Boat safari (optional)'] },
          { dayNumber: 2, title: 'Bentota Day & Surrounds', location: 'Bentota', description: 'Beaches and water sports. Brief Garden. Mask museum / market stalls.', stops: ['Beaches & water sports', 'Brief Garden', 'Mask museum / market stalls'] },
          { dayNumber: 3, title: 'Bentota/Hikkaduwa/Unawatuna — Beach Relaxation & Water Sports', location: 'Bentota', description: 'Full day of beach relaxation and/or activities and exploration.', stops: ['Bentota / Hikkaduwa / Unawatuna beach relaxation & water sports'] },
          { dayNumber: 4, title: 'Hikkaduwa/Unawatuna', location: 'Bentota / Galle', description: 'Hikkaduwa National Park coral reef. Tsunami museum.', stops: ['Hikkaduwa National Park reef', 'Tsunami museum'] },
          { dayNumber: 5, title: 'Unawatuna & Kosgoda', location: 'Bentota / Galle', description: 'Turtle Conservation Project. Jungle Beach or other beaches.', stops: ['Turtle Conservation Project', 'Jungle Beach'] },
          { dayNumber: 6, title: 'Mirissa', location: 'Galle / Mirissa', description: 'Whale watching in Mirissa. Beach activities.', stops: ['Whale watching — Mirissa', 'Beach activities'] },
          { dayNumber: 7, title: 'Galle & Coastal Exploration', location: 'Galle', description: 'Explore Galle Fort. Relaxed coastal afternoon. Coconut Tree Hill for sunset.', stops: ['Galle Fort', 'Coastal afternoon', 'Coconut Tree Hill sunset'] },
          { dayNumber: 8, title: 'Koggala & Dikwella', location: 'South Coast', description: 'Boat safari to Cinnamon Island. Stilt fishermen, turtles, Hiriketiya Bay. Cooking classes.', stops: ['Cinnamon Island boat safari', 'Stilt fishermen', 'Turtles', 'Hiriketiya Bay', 'Cooking classes'] },
          { dayNumber: 9, title: 'Dikwella / Weligama Bay', location: 'South Coast', description: 'Beach relaxation and activities. Blue Beach Island, Nilwella.', stops: ['Dikwella / Weligama bay', 'Blue Beach Island', 'Nilwella'] },
          { dayNumber: 10, title: 'Weligama/Dikwella & Surrounds', location: 'South Coast', description: 'Beach relaxation and activities.', stops: ['Weligama / Dikwella beach relaxation & activities'] },
          { dayNumber: 11, title: 'Weligama Bay/Matara', location: 'South Coast', description: 'Beach hopping and experiencing local culture.', stops: ['Beach hopping', 'Local culture — Matara'] },
          { dayNumber: 12, title: 'Tangalle', location: 'South Coast', description: 'Beach and surfing.', stops: ['Tangalle beach', 'Surfing'] },
          { dayNumber: 13, title: 'Tangalle Beach Relaxation', location: 'South Coast', description: 'Relax at Goyambokka or Silent Beach.', stops: ['Goyambokka Beach', 'Silent Beach'] },
          { dayNumber: 14, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 5: Beach Life — East Coast ─────────────────────────────────────────
  {
    groupId: 'group-beach-life-east-coast',
    groupSlug: 'beach-life-east-coast',
    name: 'Beach Life: East Coast',
    tagline: 'Just beaches, water-based activities and relaxation.',
    description: 'Crystal-clear waters, world-class marine life, legendary surf and untouched shores — Sri Lanka\'s east coast is a tropical paradise waiting to be discovered.',
    bestFor: 'Visitors seeking sun & fun across picturesque coastal vistas',
    regions: ['East Coast', 'Trincomalee', 'Arugam Bay'],
    difficulty: 'Easy',
    heroImages: ['https://images.unsplash.com/photo-1519046904884-53103b34b206?w=1200&q=80'],
    highlights: ['Beach Vibes', 'Relaxation', 'Water Activities'],
    sortOrder: 5,
    variants: [
      {
        id: 'beach-life-east-coast-5d', slug: 'beach-life-east-coast-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Trincomalee', location: 'Trincomalee', description: 'Travel east with optional stops on the way. Relax at Nilaveli/Uppuveli Beaches.', stops: ['Optional stops en route', 'Nilaveli / Uppuveli beaches'] },
          { dayNumber: 2, title: 'Trinco: Pigeon Island & Marine Life', location: 'Trincomalee', description: 'Boat ride to Pigeon Island National Park — snorkelling, diving and swimming with marine life. Visit Red-Sand Beach, Arisimale.', stops: ['Pigeon Island National Park', 'Snorkelling / diving / swim', 'Red-Sand Beach Arisimale'] },
          { dayNumber: 3, title: 'Trincomalee Sightseeing & Relax', location: 'Trincomalee', description: 'Whale watching at Swami Rock. Koneswaram Temple (optional). Fort Frederick "Deer Fort" (optional). Kanniya Hot Springs.', stops: ['Whale watching — Swami Rock', 'Koneswaram Temple (optional)', 'Fort Frederick / Deer Fort (optional)', 'Kanniya Hot Springs'] },
          { dayNumber: 4, title: 'Trincomalee → Pasikudah', location: 'Pasikudah', description: 'Beach activities. Visit Batticaloa Fort / Kallady Bridge.', stops: ['Pasikudah beach activities', 'Batticaloa Fort', 'Kallady Bridge'] },
          { dayNumber: 5, title: 'Pasikudah → Colombo', location: 'Colombo', description: 'Final morning on the beach (optional). Return to Colombo / airport. Explore en route if time.', stops: ['Final beach morning (optional)', 'En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-east-coast-7d', slug: 'beach-life-east-coast-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Trincomalee', location: 'Trincomalee', description: 'Travel east with optional stops. Relax at Nilaveli/Uppuveli.', stops: ['Optional stops en route', 'Nilaveli / Uppuveli'] },
          { dayNumber: 2, title: 'Trinco: Pigeon Island', location: 'Trincomalee', description: 'Whale watching at Swami Rock. Boat ride to Pigeon Island — snorkelling, diving, swimming. Red-Sand Beach (Arisimale).', stops: ['Whale watching — Swami Rock', 'Pigeon Island boat ride', 'Snorkelling / diving / swim', 'Red-Sand Beach Arisimale'] },
          { dayNumber: 3, title: 'Nilaveli → Pasikudah', location: 'Pasikudah', description: 'Morning swim at Nilaveli beach. Beach activities. Drive to Pasikudah.', stops: ['Nilaveli beach morning swim', 'Pasikudah beach activities'] },
          { dayNumber: 4, title: 'Pasikudah (Beach Day)', location: 'Pasikudah', description: 'Relax on the beach. Visit the quieter Kalkudah beach. Optional visit to Batticaloa Fort / Kallady Bridge.', stops: ['Pasikudah beach', 'Kalkudah beach', 'Batticaloa Fort / Kallady Bridge (optional)'] },
          { dayNumber: 5, title: 'Pasikudah → Arugam Bay', location: 'Arugam Bay', description: 'Relax on the beach and enjoy beachfront cafes or seafood shacks.', stops: ['Arugam Bay beach', 'Beachfront cafes / seafood shacks'] },
          { dayNumber: 6, title: 'Arugam Bay — Surf and Sunsets', location: 'Arugam Bay', description: 'Surf lesson at "Main Point" or "Whiskey Point", or watch the pros. Hike up to Elephant Rock (optional).', stops: ['Surf lesson — Main Point / Whiskey Point', 'Elephant Rock hike (optional)'] },
          { dayNumber: 7, title: 'Arugam Bay → Colombo', location: 'Colombo', description: 'Final morning on the beach. Return to Colombo / airport. Explore en route if time.', stops: ['Final beach morning', 'En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-east-coast-10d', slug: 'beach-life-east-coast-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Trincomalee', location: 'Trincomalee', description: 'Travel east with optional stops. Relax at Nilaveli/Uppuveli.', stops: ['Optional stops en route', 'Nilaveli / Uppuveli'] },
          { dayNumber: 2, title: 'Trinco (Nilaveli & Uppuveli)', location: 'Trincomalee', description: 'Full beach day at Nilaveli / Uppuveli and other local beaches. Red-Sand Beach (Arisimale).', stops: ['Nilaveli / Uppuveli beaches', 'Red-Sand Beach Arisimale'] },
          { dayNumber: 3, title: 'Trinco: Pigeon Island', location: 'Trincomalee', description: 'Boat ride to Pigeon Island — snorkelling, diving, swimming. Visit Fort Frederick "Deer Fort" and Kanniya Hot Springs (optional).', stops: ['Pigeon Island boat ride', 'Snorkelling / diving / swim', 'Fort Frederick / Deer Fort (optional)', 'Kanniya Hot Springs (optional)'] },
          { dayNumber: 4, title: 'Trinco Exploration — Whale & Dolphin Watching & Swami Rock', location: 'Trincomalee', description: 'Whale and dolphin watching boat ride. Swami Rock. Snorkelling at Coral Island. Visit local cultural sites (optional).', stops: ['Whale & dolphin watching boat ride', 'Swami Rock', 'Coral Island snorkelling', 'Local cultural sites (optional)'] },
          { dayNumber: 5, title: 'Trincomalee → Pasikudah', location: 'Pasikudah', description: 'Relax at Pasikudah / Kalkudah. Reef snorkelling and water sports.', stops: ['Pasikudah / Kalkudah beaches', 'Reef snorkelling', 'Water sports'] },
          { dayNumber: 6, title: 'Pasikudah (Beach Day)', location: 'Pasikudah', description: 'Relax and explore beaches. Visit Batticaloa Fort / Kallady Bridge (optional).', stops: ['Pasikudah beaches', 'Batticaloa Fort / Kallady Bridge (optional)'] },
          { dayNumber: 7, title: 'Pasikudah/Batticaloa & Optional Day Trips', location: 'Pasikudah', description: 'Batticaloa Lagoon boat ride. Batticaloa Fort / Kallady (optional).', stops: ['Batticaloa Lagoon boat ride', 'Batticaloa Fort / Kallady (optional)'] },
          { dayNumber: 8, title: 'Pasikudah → Arugam Bay', location: 'Arugam Bay', description: 'Relax on the beach and enjoy beachfront cafes or seafood shacks.', stops: ['Arugam Bay beach', 'Beachfront cafes / seafood shacks'] },
          { dayNumber: 9, title: 'Arugam Bay', location: 'Arugam Bay', description: 'Beach relaxation. Surf lesson or watch the pros. Hike up to Elephant Rock.', stops: ['Beach relaxation', 'Surf lesson / watch pros', 'Elephant Rock hike'] },
          { dayNumber: 10, title: 'Arugam Bay → Colombo', location: 'Colombo', description: 'Final morning on the beach. Return to Colombo / airport. Explore en route if time.', stops: ['Final beach morning', 'En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'beach-life-east-coast-14d', slug: 'beach-life-east-coast-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Trincomalee', location: 'Trincomalee', description: 'Travel east with optional stops. Relax at Nilaveli/Uppuveli.', stops: ['Optional stops en route', 'Nilaveli / Uppuveli'] },
          { dayNumber: 2, title: 'Trinco (Nilaveli & Uppuveli)', location: 'Trincomalee', description: 'Full beach day at Nilaveli / Uppuveli and other local beaches. Red-Sand Beach (Arisimale).', stops: ['Nilaveli / Uppuveli beaches', 'Red-Sand Beach Arisimale'] },
          { dayNumber: 3, title: 'Trinco: Pigeon Island', location: 'Trincomalee', description: 'Boat ride to Pigeon Island — snorkelling, diving, swimming. Fort Frederick "Deer Fort". Kanniya Hot Springs (optional).', stops: ['Pigeon Island boat ride', 'Snorkelling / diving / swim', 'Fort Frederick / Deer Fort', 'Kanniya Hot Springs (optional)'] },
          { dayNumber: 4, title: 'Trinco: Whale & Dolphin Watching', location: 'Trincomalee', description: 'Boat ride and Swami Rock. Snorkelling at Coral Island. Local cultural and religious sites (optional).', stops: ['Boat ride — Swami Rock', 'Coral Island snorkelling', 'Local cultural & religious sites (optional)'] },
          { dayNumber: 5, title: 'Trincomalee Exploration', location: 'Trincomalee', description: 'Koneswaram Temple (optional). Fort Frederick "Deer Fort" (optional). Kanniya Hot Springs (optional).', stops: ['Koneswaram Temple (optional)', 'Fort Frederick / Deer Fort (optional)', 'Kanniya Hot Springs (optional)'] },
          { dayNumber: 6, title: 'Trincomalee Relaxation', location: 'Trincomalee', description: 'Relax on Trincomalee and Uppuveli beaches.', stops: ['Trincomalee beaches', 'Uppuveli beach'] },
          { dayNumber: 7, title: 'Trincomalee → Pasikudah Bay', location: 'Pasikudah', description: 'Relax at Pasikudah / Kalkudah. Reef snorkelling and water sports.', stops: ['Pasikudah / Kalkudah beaches', 'Reef snorkelling', 'Water sports'] },
          { dayNumber: 8, title: 'Pasikudah (Beach Day)', location: 'Pasikudah', description: 'Relax and explore beaches. Visit Batticaloa Fort / Kallady Bridge (optional).', stops: ['Pasikudah beaches', 'Batticaloa Fort / Kallady Bridge (optional)'] },
          { dayNumber: 9, title: 'Pasikudah/Batticaloa & Optional Day Trips', location: 'Pasikudah', description: 'Batticaloa Lagoon boat ride. Batticaloa Fort / Kallady Bridge or day trips inland (optional).', stops: ['Batticaloa Lagoon boat ride', 'Batticaloa Fort / Kallady Bridge (optional)', 'Day trips inland (optional)'] },
          { dayNumber: 10, title: 'Pasikudah → Arugam Bay', location: 'Arugam Bay', description: 'Relax on the beach and enjoy beachfront cafes or seafood shacks.', stops: ['Arugam Bay beach', 'Beachfront cafes / seafood shacks'] },
          { dayNumber: 11, title: 'Arugam Bay', location: 'Arugam Bay', description: 'Beach relaxation. Surf lesson or watch the pros. Hike up to Elephant Rock.', stops: ['Beach relaxation', 'Surf lesson / watch pros', 'Elephant Rock hike'] },
          { dayNumber: 12, title: 'Arugam Bay / Pottuvil & Local', location: 'Arugam Bay', description: 'Pottuvil Lagoon boat safari. Kumana National Park and/or local cooking class.', stops: ['Pottuvil Lagoon boat safari', 'Kumana National Park', 'Local cooking class'] },
          { dayNumber: 13, title: 'Arugam Bay — Final Beach Day', location: 'Arugam Bay', description: 'Beach relaxation. Surfing and/or local exploration.', stops: ['Beach relaxation', 'Surfing', 'Local exploration'] },
          { dayNumber: 14, title: 'Arugam Bay → Colombo', location: 'Colombo', description: 'Return to Colombo / airport.', stops: ['Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 6: Scenery & Nature Sri Lanka ──────────────────────────────────────
  {
    groupId: 'group-scenery-nature-sri-lanka',
    groupSlug: 'scenery-nature-sri-lanka',
    name: 'Scenery & Nature Sri Lanka',
    tagline: 'Waterfalls, mountains, landscapes and wildlife.',
    description: 'Sri Lanka\'s most breathtaking natural wonders — from misty tea country and the Nine Arches Bridge to elephant safaris, the Sinharaja rainforest and whale watching on the south coast.',
    bestFor: 'Adventure, nature lovers, eco-tourists, hikers, couples',
    regions: ['Hill Country', 'Wildlife Parks', 'South Coast'],
    difficulty: 'Moderate',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69838bc1712205ff655de71c_5052216621-ezgif.com-webp-to-jpg-converter.jpg'],
    highlights: ['Mountains', 'Waterfalls', 'Landscapes', 'Wildlife'],
    sortOrder: 6,
    variants: [
      {
        id: 'scenery-nature-sri-lanka-5d', slug: 'scenery-nature-sri-lanka-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Kandy', location: 'Kandy', description: 'Travel via scenic countryside. Evening: Temple of the Tooth.', stops: ['Scenic countryside drive', 'Temple of the Tooth'] },
          { dayNumber: 2, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Tea plantations and factory visit. Cooler climate and beautiful waterfalls.', stops: ['Tea plantations & factory', 'Waterfalls', 'Nuwara Eliya'] },
          { dayNumber: 3, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic Kandy to Ella train (*check availability). Visit Nine Arches Bridge.', stops: ['Kandy to Ella scenic train (*check availability)', 'Nine Arches Bridge'] },
          { dayNumber: 4, title: 'Ella Exploration & Nature Walks', location: 'Ella', description: 'Hike Little Adam\'s Peak. Explore Ella\'s beautiful waterfalls.', stops: ['Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 5, title: 'Ella → Colombo', location: 'Colombo', description: 'Drive back via scenic mountain roads. Optional stops en route at tourist request.', stops: ['Scenic mountain road drive', 'Optional stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'scenery-nature-sri-lanka-7d', slug: 'scenery-nature-sri-lanka-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Kandy', location: 'Kandy', description: 'Travel via scenic countryside. Relax and explore.', stops: ['Scenic countryside drive', 'Kandy'] },
          { dayNumber: 2, title: 'Kandy Exploration', location: 'Kandy', description: 'Temple of the Tooth. Royal Botanic Gardens. Cultural dance show.', stops: ['Temple of the Tooth', 'Royal Botanic Gardens', 'Cultural dance show'] },
          { dayNumber: 3, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Tea plantations and factory visit. Cooler climate and waterfalls.', stops: ['Tea plantations & factory', 'Cooler climate & waterfalls'] },
          { dayNumber: 4, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Visit waterfalls, tea estates and scenic viewpoints.', stops: ['Waterfalls', 'Tea estates', 'Scenic viewpoints'] },
          { dayNumber: 5, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic train journey to Ella (*check availability).', stops: ['Scenic train to Ella (*check availability)'] },
          { dayNumber: 6, title: 'Ella Exploration & Nature', location: 'Ella', description: 'Visit Nine Arches Bridge. Hike Little Adam\'s Peak. Explore waterfalls.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 7, title: 'Ella → Colombo', location: 'Colombo', description: 'Drive via scenic route with optional stops en route.', stops: ['Scenic route drive', 'Optional stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'scenery-nature-sri-lanka-10d', slug: 'scenery-nature-sri-lanka-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Kandy', location: 'Kandy', description: 'Travel via scenic countryside. Relax and explore.', stops: ['Scenic countryside drive', 'Kandy'] },
          { dayNumber: 2, title: 'Kandy Exploration', location: 'Kandy', description: 'Temple of the Tooth. Royal Botanic Gardens. Cultural dance show.', stops: ['Temple of the Tooth', 'Royal Botanic Gardens', 'Cultural dance show'] },
          { dayNumber: 3, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Tea plantations and factory visit. Cooler climate and waterfalls.', stops: ['Tea plantations & factory', 'Cooler climate & waterfalls'] },
          { dayNumber: 4, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Waterfalls, tea estates and scenic viewpoints.', stops: ['Waterfalls', 'Tea estates', 'Scenic viewpoints'] },
          { dayNumber: 5, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic train journey to Ella (*check availability).', stops: ['Scenic train to Ella (*check availability)'] },
          { dayNumber: 6, title: 'Ella Exploration & Nature', location: 'Ella', description: 'Visit Nine Arches Bridge. Hike Little Adam\'s Peak. Explore waterfalls.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 7, title: 'Ella → Udawalawe Safari', location: 'Ella / Udawalawe', description: 'Safari at Udawalawe National Park.', stops: ['Udawalawe National Park safari'] },
          { dayNumber: 8, title: 'Udawalawe → Sinharaja Rainforest', location: 'Sinharaja', description: 'Travel to the Sinharaja rainforest region.', stops: ['Sinharaja rainforest'] },
          { dayNumber: 9, title: 'Sinharaja Nature Experience', location: 'Sinharaja', description: 'Explore Sinharaja biodiversity and trails.', stops: ['Sinharaja biodiversity trails'] },
          { dayNumber: 10, title: 'Sinharaja → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
      {
        id: 'scenery-nature-sri-lanka-14d', slug: 'scenery-nature-sri-lanka-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(48, 65, 88, 122, 170), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → Kandy', location: 'Kandy', description: 'Travel via scenic countryside. Relax and explore.', stops: ['Scenic countryside drive', 'Kandy'] },
          { dayNumber: 2, title: 'Kandy Exploration', location: 'Kandy', description: 'Temple of the Tooth. Royal Botanic Gardens. Cultural dance show.', stops: ['Temple of the Tooth', 'Royal Botanic Gardens', 'Cultural dance show'] },
          { dayNumber: 3, title: 'Kandy → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Tea plantations and factory visit. Cooler climate and waterfalls.', stops: ['Tea plantations & factory', 'Cooler climate & waterfalls'] },
          { dayNumber: 4, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Waterfalls, tea estates and scenic viewpoints.', stops: ['Waterfalls', 'Tea estates', 'Scenic viewpoints'] },
          { dayNumber: 5, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic train journey to Ella (*check availability).', stops: ['Scenic train to Ella (*check availability)'] },
          { dayNumber: 6, title: 'Ella Exploration & Nature', location: 'Ella', description: 'Visit Nine Arches Bridge. Hike Little Adam\'s Peak. Explore waterfalls.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 7, title: 'Ella → Udawalawe Safari', location: 'Ella / Udawalawe', description: 'Safari at Udawalawe National Park.', stops: ['Udawalawe National Park safari'] },
          { dayNumber: 8, title: 'Udawalawe → Yala National Park', location: 'Yala', description: 'Travel to Yala National Park.', stops: ['Yala National Park'] },
          { dayNumber: 9, title: 'Yala Safari Experience', location: 'Yala', description: 'Enjoy wildlife encounters in Yala — leopards, elephants, sloth bears and birdlife.', stops: ['Yala wildlife safari — leopards, elephants, sloth bears'] },
          { dayNumber: 10, title: 'Yala → Sinharaja Rainforest', location: 'Sinharaja', description: 'Travel to the Sinharaja rainforest region.', stops: ['Sinharaja rainforest'] },
          { dayNumber: 11, title: 'Sinharaja Exploration', location: 'Sinharaja', description: 'Guided rainforest trekking.', stops: ['Guided rainforest trekking — Sinharaja'] },
          { dayNumber: 12, title: 'Sinharaja → Koggala & Dikwella', location: 'South Coast / Galle', description: 'Boat safari to Cinnamon Island. Stilt fishermen, turtles, Hiriketiya Bay.', stops: ['Cinnamon Island boat safari', 'Stilt fishermen', 'Turtles', 'Hiriketiya Bay'] },
          { dayNumber: 13, title: 'Mirissa & Galle', location: 'South Coast / Galle / Mirissa', description: 'Whale watching in Mirissa. Coconut Tree Hill for sunset. Beach and local scenery.', stops: ['Whale watching — Mirissa', 'Coconut Tree Hill sunset', 'Beach & local scenery'] },
          { dayNumber: 14, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo with optional stops along the way.', stops: ['Optional stops en route', 'Colombo / airport'] },
        ],
      },
    ],
  },

  // ── Tour 7: Honeymoon, Wedding & Romance Sri Lanka ───────────────────────────
  {
    groupId: 'group-honeymoon-wedding-romance',
    groupSlug: 'honeymoon-wedding-romance',
    name: 'Honeymoon, Wedding & Romance',
    tagline: 'Romantic & scenic — picturesque moments across Sri Lanka.',
    description: 'Designed for couples — private sunset walks along golden shores, whale watching in Mirissa, misty tea country, and the most romantic vistas Sri Lanka has to offer.',
    bestFor: 'Couples — intimacy, beauty, unforgettable memories',
    regions: ['South Coast', 'Hill Country', 'Galle'],
    difficulty: 'Easy',
    heroImages: ['https://cdn.prod.website-files.com/68fe492bc39e0e661cce824d/69f027d4583402df5a085c94_Honeymoon.png'],
    highlights: ['Romantic Retreat', 'Scenic Views', 'Private Moments'],
    sortOrder: 7,
    variants: [
      {
        id: 'honeymoon-wedding-romance-5d', slug: 'honeymoon-wedding-romance-5d',
        durationDays: 5, durationNights: 4,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast (Bentota/Mirissa)', location: 'Bentota / Mirissa', description: 'Leisure evening — unwind together by the sea.', stops: ['South Coast (Bentota/Mirissa)', 'Leisurely evening'] },
          { dayNumber: 2, title: 'Bentota/Hikkaduwa/Unawatuna — Beach Relax & Sunset Moments', location: 'Bentota / Mirissa', description: 'Beaches and optional water sports. Private sunset walk along the shore.', stops: ['Bentota / Hikkaduwa / Unawatuna beaches', 'Optional water sports', 'Private sunset walk'] },
          { dayNumber: 3, title: 'Galle Fort & Coastal Strolls', location: 'Galle', description: 'Explore Galle Fort, relax in the streets and cafes. Coconut Tree Hill for sunset. Whale watching in Mirissa if time allows.', stops: ['Galle Fort', 'Streets & cafes', 'Coconut Tree Hill sunset', 'Whale watching — Mirissa (if time)'] },
          { dayNumber: 4, title: 'Tangalle Beach Relaxation', location: 'Galle / Tangalle', description: 'Relax at Goyambokka or Silent Beach. Optional spa, massage and boat cruises.', stops: ['Goyambokka Beach', 'Silent Beach', 'Spa / massage / boat cruises (optional)'] },
          { dayNumber: 5, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time available.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'honeymoon-wedding-romance-7d', slug: 'honeymoon-wedding-romance-7d',
        durationDays: 7, durationNights: 6,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast (Bentota/Mirissa)', location: 'Bentota / Mirissa', description: 'Leisurely evening by the sea.', stops: ['South Coast (Bentota/Mirissa)', 'Leisurely evening'] },
          { dayNumber: 2, title: 'Bentota/Hikkaduwa/Unawatuna — Beach Relax & Sunset Moments', location: 'Bentota', description: 'Beaches and optional water sports. Private sunset walk along the shore.', stops: ['Bentota / Hikkaduwa / Unawatuna beaches', 'Optional water sports', 'Private sunset walk'] },
          { dayNumber: 3, title: 'Mirissa & Galle', location: 'Galle', description: 'Whale watching in Mirissa. Relax by the sea. Goyambokka or Silent Beach.', stops: ['Whale watching — Mirissa', 'Relax by the sea', 'Goyambokka / Silent Beach'] },
          { dayNumber: 4, title: 'Galle Fort & Coastal Strolls', location: 'Galle', description: 'Explore Galle Fort — romantic streets, cafes and viewpoints. Coconut Tree Hill for sunset.', stops: ['Galle Fort', 'Romantic streets & cafes', 'Coconut Tree Hill sunset'] },
          { dayNumber: 5, title: 'South Coast → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Travel inland to the scenic tea country.', stops: ['Scenic tea country drive', 'Nuwara Eliya'] },
          { dayNumber: 6, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Visit waterfalls, tea estates and panoramic landscapes together.', stops: ['Waterfalls', 'Tea estates', 'Panoramic landscapes'] },
          { dayNumber: 7, title: 'Nuwara Eliya → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'honeymoon-wedding-romance-10d', slug: 'honeymoon-wedding-romance-10d',
        durationDays: 10, durationNights: 9,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast (Bentota/Mirissa)', location: 'Bentota / Mirissa', description: 'Leisurely evening by the sea.', stops: ['South Coast (Bentota/Mirissa)', 'Leisurely evening'] },
          { dayNumber: 2, title: 'Bentota Day & Surrounds', location: 'Bentota', description: 'Beaches and water sports. Brief Garden. Mask museum / market stalls.', stops: ['Beaches & water sports', 'Brief Garden', 'Mask museum / market stalls'] },
          { dayNumber: 3, title: 'Mirissa & Galle', location: 'Galle', description: 'Whale watching in Mirissa. Relax by the sea. Explore local life and culture.', stops: ['Whale watching — Mirissa', 'Relax by the sea', 'Local life & culture'] },
          { dayNumber: 4, title: 'Galle Fort & Coastal Strolls', location: 'Galle', description: 'Explore Galle Fort — romantic streets, cafes and viewpoints. Coconut Tree Hill for sunset.', stops: ['Galle Fort', 'Romantic streets & cafes', 'Coconut Tree Hill sunset'] },
          { dayNumber: 5, title: 'South Coast → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Travel inland to the scenic tea country.', stops: ['Scenic tea country drive', 'Nuwara Eliya'] },
          { dayNumber: 6, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Visit waterfalls, lakes and tea plantations together.', stops: ['Waterfalls', 'Lakes', 'Tea plantations'] },
          { dayNumber: 7, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic train journey to Ella (*check availability).', stops: ['Scenic train to Ella (*check availability)'] },
          { dayNumber: 8, title: 'Ella Exploration', location: 'Ella', description: 'Visit Nine Arches Bridge. Hike Little Adam\'s Peak. Explore waterfalls.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 9, title: 'Ella → Tangalle/South Coast Beach Relaxation', location: 'South Coast', description: 'Relax at Goyambokka or Silent Beach.', stops: ['Goyambokka Beach', 'Silent Beach'] },
          { dayNumber: 10, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
      {
        id: 'honeymoon-wedding-romance-14d', slug: 'honeymoon-wedding-romance-14d',
        durationDays: 14, durationNights: 13,
        vehicleRates: VR(55, 75, 100, 140, 195), isActive: true,
        itinerary: [
          { dayNumber: 1, title: 'Colombo → South Coast (Bentota/Mirissa)', location: 'Bentota / Mirissa', description: 'Leisurely evening by the sea.', stops: ['South Coast (Bentota/Mirissa)', 'Leisurely evening'] },
          { dayNumber: 2, title: 'Bentota Day & Surrounds', location: 'Bentota', description: 'Beaches and water sports. Brief Garden. Mask museum / market stalls.', stops: ['Beaches & water sports', 'Brief Garden', 'Mask museum / market stalls'] },
          { dayNumber: 3, title: 'Mirissa & Galle', location: 'Galle', description: 'Whale watching in Mirissa. Relax by the sea. Explore local life and culture.', stops: ['Whale watching — Mirissa', 'Relax by the sea', 'Local life & culture'] },
          { dayNumber: 4, title: 'Galle Fort & Coastal Exploration', location: 'Galle', description: 'Explore Galle Fort — romantic streets, cafes and viewpoints. Coconut Tree Hill for sunset.', stops: ['Galle Fort', 'Romantic streets & cafes', 'Coconut Tree Hill sunset'] },
          { dayNumber: 5, title: 'South Coast → Nuwara Eliya', location: 'Nuwara Eliya', description: 'Travel inland to the scenic tea country.', stops: ['Scenic tea country drive', 'Nuwara Eliya'] },
          { dayNumber: 6, title: 'Nuwara Eliya Exploration', location: 'Nuwara Eliya', description: 'Visit waterfalls, lakes and tea plantations together.', stops: ['Waterfalls', 'Lakes', 'Tea plantations'] },
          { dayNumber: 7, title: 'Nuwara Eliya → Ella', location: 'Ella', description: 'Scenic train journey to Ella (*check availability).', stops: ['Scenic train to Ella (*check availability)'] },
          { dayNumber: 8, title: 'Ella Nature & Viewpoints', location: 'Ella', description: 'Visit Nine Arches Bridge. Hike Little Adam\'s Peak. Explore waterfalls.', stops: ['Nine Arches Bridge', 'Little Adam\'s Peak hike', 'Ella waterfalls'] },
          { dayNumber: 9, title: 'Ella → Udawalawe Safari', location: 'Udawalawe', description: 'Enjoy wildlife together at a safari in Udawalawe National Park.', stops: ['Udawalawe National Park safari'] },
          { dayNumber: 10, title: 'Udawalawe → Yala National Park', location: 'Yala', description: 'Safari at Yala National Park.', stops: ['Yala National Park safari'] },
          { dayNumber: 11, title: 'Yala → Tangalle', location: 'South Coast', description: 'Relax at Goyambokka or Silent Beach.', stops: ['Goyambokka Beach', 'Silent Beach'] },
          { dayNumber: 12, title: 'Tangalle → Dikwella/Weligama', location: 'South Coast', description: 'Beach and surfing.', stops: ['Dikwella / Weligama beach', 'Surfing'] },
          { dayNumber: 13, title: 'Dikwella / Weligama Bay', location: 'South Coast', description: 'Beach relaxation and activities. Blue Beach Island, Nilwella.', stops: ['Dikwella / Weligama bay', 'Blue Beach Island', 'Nilwella'] },
          { dayNumber: 14, title: 'South Coast → Colombo', location: 'Colombo', description: 'Return to Colombo / airport. Explore en route if time.', stops: ['En route exploration (if time)', 'Colombo / airport'] },
        ],
      },
    ],
  },
];
